"use strict";
const assert = require("node:assert/strict");
const helpers = require("./app.js");
let checks = 0;
function equal(actual, expected) { checks++; assert.deepEqual(actual, expected); }

equal(helpers.channelId(''), null);
equal(helpers.channelId(null), null);
equal(helpers.channelId(' -1001234567890 '), -1001234567890);
equal(helpers.channelId(-1001234567890), -1001234567890);
for (const value of ['@channel', 'https://t.me/c/1234567890/1', '-1234', '-1000', '-100123.4', '-1001e10', '-100123456789012345', {}, true]) { checks++; assert.throws(() => helpers.channelId(value)); }
equal(helpers.channelState(null), ['Chưa gán channel', 'amber']);
equal(helpers.channelState({channel_chat_id: -100123, channel_status: 'ready'}), ['Channel sẵn sàng', 'green']);
equal(helpers.channelState({channel_chat_id: -100123, channel_status: 'error'}), ['Cần kiểm tra quyền bot', 'red']);
equal(helpers.channelState({channel_chat_id: -100123}), ['Chưa kiểm tra channel', 'amber']);
equal(helpers.channelState({channel_chat_id: -100123, channel_enabled: false, channel_status: 'ready'}), ['Channel tạm dừng', 'neutral']);
equal(helpers.channelIndexUrl('https://t.me/c/1234567890/34'), 'https://t.me/c/1234567890/34');
for (const url of ['http://t.me/c/123/4', 'https://t.me.evil/c/123/4', 'https://x@t.me/c/123/4', 'https://t.me:8080/c/123/4', 'https://t.me/c/123/4?a=b', 'https://t.me/c/123/4#fragment', 'javascript:alert(1)', 'https://t.me/c/0/4', null]) equal(helpers.channelIndexUrl(url), null);
equal(helpers.cameraPatch({channel_chat_id: null, channel_enabled: true}, {channel_chat_id: -1001234567890, channel_enabled: false}), {channel_chat_id: -1001234567890, channel_enabled: false});
equal(helpers.cameraPatch({channel_chat_id: -1001234567890}, {channel_chat_id: null}), {channel_chat_id: null});
equal(helpers.formatBytes(null), "—");
equal(helpers.formatBytes(undefined), "—");
equal(helpers.formatBytes("n/a"), "—");
equal(helpers.formatBytes(-1), "—");
equal(helpers.formatBytes(0), "0 B");
equal(helpers.formatBytes(1024), "1 KB");
equal(helpers.formatBytes(1024 * 1024), "1 MB");
equal(helpers.formatDuration(0, 45000), "45 giây");
equal(helpers.formatDuration(0, 65000), "1 phút 5 giây");
equal(helpers.formatDuration(0, 120000), "2 phút");
equal(helpers.formatDuration(5000, 0), "—");
equal(helpers.formatDuration(null, 0), "—");
const privateLink = "https://t.me/fixture_archive_bot?start=play_" + "a".repeat(32);
equal(helpers.telegramUrl(privateLink), privateLink);
for (const url of ["https://t.me/c/12345/17", privateLink + "&extra=1", privateLink + "#fragment", privateLink.replace("play_", "other_"), privateLink.slice(0, -1), "https://t.me/fixture_archive_bot", privateLink.replace("fixture_archive_bot", "tiny")]) equal(helpers.telegramUrl(url), null);
for (const url of ["javascript:alert(1)", "http://t.me/c/1/2", "https://t.me.evil.example/c/1/2", "https://evil.example/t.me", "https://evil:t.me@t.me/c/1/2", "https://t.me:444/c/1/2", "https://t.me/", null]) equal(helpers.telegramUrl(url), null);
for (const host of ["192.168.1.11", "192.168.1.10", "camera-h6c.local", "camera", "CAMERA-1"]) equal(helpers.validHost(host), true);
for (const host of ["999.168.31.137", "192.168.1.1000", "http://192.168.1.11", "camera.local/path", "camera:8000", "user@camera", "-camera.local", "camera..local", "", "<img>", null]) equal(helpers.validHost(host), false);
equal(helpers.status("uploaded"), ["Đã lưu Telegram", "green"]);
equal(helpers.status("upload_unknown"), ["Cần đối chiếu upload", "amber"]);
equal(helpers.status("needs_review"), ["Cần kiểm tra", "amber"]);
equal(helpers.status("UNRECOGNIZED"), ["UNRECOGNIZED", "neutral"]);
equal(helpers.probeState(true), ["Mở", "green"]);
equal(helpers.probeState({open: true}), ["Mở", "green"]);
equal(helpers.probeState({status: "open"}), ["Mở", "green"]);
equal(helpers.probeState(false), ["Đóng / không phản hồi", "red"]);
equal(helpers.probeState(undefined), ["Chưa kiểm tra", "neutral"]);
equal(helpers.probeState("unconfirmed"), ["Chưa xác nhận", "amber"]);
equal(helpers.checkedMillis(1790989200), 1790989200000);
equal(helpers.checkedMillis("2026-10-03T00:00:00Z"), Date.parse("2026-10-03T00:00:00Z"));
equal(helpers.checkedMillis("bad"), null);
equal(helpers.checkedMillis(null), null);
equal(helpers.cameraCount({counts: {total: 5, uploaded: 4}}, "total"), 5);
equal(helpers.cameraCount({counts: {total: 5, uploaded: 4}}, "uploaded"), 4);
equal(helpers.cameraCount({record_count: 0}, "total"), 0);
equal(helpers.cameraCount({}, "total"), null);
for (const job of [null, {}, {updated_at: "bad"}, {updated_at: Infinity}, {updated_at: 1e30}]) equal(helpers.syncUpdated(job, 100000), "");
equal(helpers.syncUpdated({updated_at: 100}, 120000), `Cập nhật 20 giây trước · ${new Date(100000).toLocaleString("vi-VN")}`);
equal(helpers.syncUpdated({updated_at: 100}, 220000), `Cập nhật 2 phút trước · ${new Date(100000).toLocaleString("vi-VN")}`);
equal(helpers.syncUpdated({updated_at: 100}, 3700000), `Cập nhật 1 giờ trước · ${new Date(100000).toLocaleString("vi-VN")}`);
equal(helpers.syncUpdated({updated_at: 200}, 100000), `Cập nhật 0 giây trước · ${new Date(200000).toLocaleString("vi-VN")}`);
equal(helpers.syncUpdated({updated_at: 100}, NaN), "");
const original = {id: "Front_Camera", name: "Cửa trước", model: "CS-H6c", host: "192.168.1.11", device_port: 8000, rtsp_port: 554, http_port: 80, enabled: true};
equal(helpers.cameraPatch(original, {...original}), {});
equal(helpers.cameraPatch(original, {...original, name: "Sân trước"}), {name: "Sân trước"});
equal(helpers.cameraPatch(original, {...original, host: "192.168.31.138"}), {host: "192.168.31.138"});
equal(helpers.cameraPatch(original, {...original, id: "Changed_Id"}), {});
equal(helpers.cameraPatch(original, {...original, enabled: false}), {enabled: false});
for (const username of ['admin', 'new.admin_1', 'A'.repeat(64)]) equal(helpers.validUsername(username), true);
for (const username of ['ab', 'A'.repeat(65), 'bad name', '<admin>', '', null]) equal(helpers.validUsername(username), false);
const credentials = {username: 'new_admin', current_password: 'admin', new_password: 'new-password-123', confirm_password: 'new-password-123'};
equal(helpers.accountValidation(credentials), null);
equal(helpers.accountValidation({...credentials, username: 'x'}).field, 'account-username');
equal(helpers.accountValidation({...credentials, current_password: ''}).field, 'account-current-password');
equal(helpers.accountValidation({...credentials, new_password: 'short', confirm_password: 'short'}).field, 'account-new-password');
equal(helpers.accountValidation({...credentials, new_password: 'x'.repeat(129)}).field, 'account-new-password');
equal(helpers.accountValidation({...credentials, confirm_password: 'different'}).field, 'account-confirm-password');
equal(helpers.accountValidation({...credentials, new_password: '🔑'.repeat(128), confirm_password: '🔑'.repeat(128)}), null);
equal(helpers.accountValidation({...credentials, new_password: '🔑'.repeat(129), confirm_password: '🔑'.repeat(129)}).field, 'account-new-password');
equal(helpers.uploadEnabled({}), true);
equal(helpers.uploadEnabled({upload_enabled: true}), true);
equal(helpers.uploadEnabled({upload_enabled: false}), false);
equal(helpers.syncActive({state: 'queued'}), true);
equal(helpers.syncActive({state: 'running'}), true);
for (const state of ['completed', 'blocked', 'failed', undefined]) equal(helpers.syncActive({state}), false);
equal(helpers.syncActive(null), false);
equal(helpers.syncState({state: 'blocked'}), ['Cần xử lý', 'amber']);
equal(helpers.syncState({state: 'completed'}), ['Hoàn tất', 'green']);
equal(helpers.syncState(null), ['Chưa Start', 'neutral']);
equal(helpers.syncPhase({phase: 'sd_download'}), 'Tải SD');
equal(helpers.syncPhase({phase: 'uploading'}), 'Upload Telegram');
equal(helpers.syncStatistics({statistics: {sd_searched: 3, sd_downloaded: 2, uploaded: 1, pending: 0, secret: 'notshown'}}), 'Tìm thấy SD: 3 · Đã tải SD: 2 · Đã upload: 1 · Chờ upload: 0');
equal(helpers.syncStatistics({statistics: {uploaded: -1, failed: NaN, imported: '3'}}), '');
equal(helpers.syncHelp({code: 'sd_sdk_missing'}).includes('/opt/hcnetsdk'), true);
equal(helpers.syncHelp({code: 'sd_network_error'}).includes('Tailscale'), true);
equal(helpers.syncHelp({code: 'sd_source_missing'}).includes('8000'), true);
equal(helpers.syncHelp({code: 'sd_credentials_missing'}).includes('mã xác thực'), true);
equal(helpers.syncHelp({code: 'complete'}), '');
equal(helpers.cameraPatch(original, {...original, upload_enabled: false}), {upload_enabled: false});
equal(helpers.cameraPatch(original, {...original, sd_password: ''}), {});
equal(helpers.cameraPatch(original, {...original, sd_password: 'fixture-password'}), {sd_password: 'fixture-password'});
equal(helpers.cameraPatch(original, {...original, sd_password_clear: true}), {sd_password_clear: true});
equal(helpers.cameraPatch(original, {...original, sd_backend: 'hcnetsdk', sd_channel: 1}), {sd_backend: 'hcnetsdk', sd_channel: 1});
equal(helpers.validSdPassword('x'.repeat(64)), true);
equal(helpers.validSdPassword('x'.repeat(65)), false);
equal(helpers.validSdPassword('🔑'.repeat(16)), true);
equal(helpers.validSdPassword('🔑'.repeat(17)), false);
equal(helpers.validSdPassword('x\0x'), false);
equal(helpers.syncSummary({}), 'Không có sync đang chạy');
equal(helpers.syncSummary({a: {state: 'running'}, b: {state: 'queued'}, c: {state: 'blocked'}, d: {state: 'failed'}, e: {state: 'completed'}}), '1 đang chạy · 1 chờ · 2 cần xử lý');
equal(helpers.syncSummary({a: null, b: {state: 'completed'}}), 'Không có sync đang chạy');
equal(helpers.syncLine(null), 'Bấm Start sync để bắt đầu');
equal(helpers.syncLine({phase: 'uploading', statistics: {sd_searched: 27, sd_downloaded: 27, uploaded: 16, failed: 0}}), 'Upload Telegram · SD 27 · Tải 27 · Upload 16 · Lỗi 0');
equal(helpers.syncLine({phase: 'sd_search', statistics: {sd_searched: 0, uploaded: '4', failed: -1, sd_downloaded: NaN}}), 'Tìm recording SD · SD 0');
equal(helpers.syncLine({phase: 'queued'}), 'Hàng đợi');
equal(helpers.syncDetailFields({statistics: {sd_backend: 'hcnetsdk', sd_downloaded: 0, remuxed: 5, sd_error_code: null}}), [['Bộ tải SD', 'hcnetsdk'], ['Đã tải SD', '0'], ['Đã remux', '5'], ['Mã lỗi SD', '—']]);
equal(helpers.syncDetailFields({statistics: {unknown_count: 4, bad: Infinity, negative: -1, object: {}, empty: '', flag: false}}), []);
equal(helpers.syncDetailFields({statistics: {uploaded: 1, secret: 'synthetic-token', token: 'synthetic-token', source_path: '/synthetic/private', sd_backend: 'hcnetsdk', sd_imported: 2}}), [['Đã upload', '1'], ['Bộ tải SD', 'hcnetsdk'], ['Đã nhập SD', '2']]);
equal(helpers.syncDetailFields({statistics: JSON.parse('{"__proto__":"synthetic-token","constructor":"synthetic-token","uploaded":0}')}), [['Đã upload', '0']]);
equal(helpers.syncDetailFields(null), []);
equal(helpers.syncDetailFields({statistics: {sd_error_code: '<img src=x onerror=alert(1)>'}}), [['Mã lỗi SD', '<img src=x onerror=alert(1)>']]);
equal(helpers.syncTimestamp(null), '—');
equal(helpers.syncTimestamp('invalid'), '—');
equal(helpers.syncTimestamp(1e30), '—');
equal(helpers.syncTimestamp(100), new Date(100000).toLocaleString('vi-VN'));
equal(helpers.syncTimestamp(100, true), new Date(100000).toLocaleString('vi-VN', {day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit'}));
const logJobs = [{id: 'one', camera_id: 'pn', state: 'running'}, {id: 'two', camera_id: 'pn', state: 'blocked'}, {id: 'three', camera_id: 'door', state: 'completed'}, {id: 'four', camera_id: 'door', state: 'queued'}, {id: 'five', camera_id: 'door', state: 'failed'}];
equal(helpers.syncLogFilter(logJobs).map(job => job.id), ['one', 'two', 'three', 'four', 'five']);
equal(helpers.syncLogFilter(logJobs, 'pn').map(job => job.id), ['one', 'two']);
equal(helpers.syncLogFilter(logJobs, '', 'active').map(job => job.id), ['one', 'four']);
equal(helpers.syncLogFilter(logJobs, '', 'errors').map(job => job.id), ['two', 'five']);
equal(helpers.syncLogFilter(logJobs, 'door', 'completed').map(job => job.id), ['three']);
equal(helpers.syncLogFilter(logJobs, 'missing').length, 0);
equal(helpers.syncLogFilter(null), []);
equal(helpers.discoveryActive({state: 'running'}), true);
equal(helpers.discoveryActive({state: 'completed'}), false);
equal(helpers.discoveryActive(null), false);
for (const [target, count] of [['192.168.31.0/24', 254], ['192.168.31.166', 1], ['10.0.0.1-10.0.0.3', 3], ['172.16.0.0/22', 1022], ['192.168.0.2/31', 2], ['192.168.0.2/32', 1]]) equal(helpers.discoveryTarget(target), {target, count});
for (const target of ['', 'example.local', '192.168.01.1', '192.168.1.256', 'http://192.168.1.1', '192.168.1.1/33', '192.168.1.1/24/24', '192.168.1.4-192.168.1.1', '192.168.1.1-192.168.1.2-192.168.1.3', '127.0.0.1', '169.254.169.254', '8.8.8.8', '100.64.0.1', '172.32.0.1', '10.0.0.0/8', '10.0.0.0/21']) equal(typeof helpers.discoveryTarget(target).error, 'string');
equal(helpers.discoveryTarget(' 192.168.31.1 - 192.168.31.3 ').count, 3);
const discoveryCamera = {host: '192.168.31.166', device_port: 8000, rtsp_port: 554, http_port: 80, model: 'CS-C6N'};
equal(helpers.discoveryKnown(discoveryCamera, [{id: 'pn', host: '192.168.31.166', device_port: 8000}]), 'pn');
equal(helpers.discoveryKnown(discoveryCamera, [{id: 'pn', host: '192.168.31.166', device_port: 9000}]), '');
equal(helpers.discoveryKnown({...discoveryCamera, existing_camera_id: 'known'}, []), 'known');
equal(helpers.discoveryKnown(discoveryCamera, null), '');
const draftDiscovery = helpers.discoveryPayload(discoveryCamera, ' Phòng ngủ ', [], 'admin', '');
equal(draftDiscovery, {id: 'cam-192-168-31-166', name: 'Phòng ngủ', model: 'CS-C6N', host: '192.168.31.166', device_port: 8000, rtsp_port: 554, http_port: 80, enabled: false, upload_enabled: true, sd_backend: 'auto', sd_username: 'admin'});
equal(helpers.discoveryPayload(discoveryCamera, 'PN', [{id: 'cam-192-168-31-166'}, {id: 'cam-192-168-31-166-2'}], ' admin ', 'fixture-password').id, 'cam-192-168-31-166-3');
const readyDiscovery = helpers.discoveryPayload(discoveryCamera, 'PN', [], 'admin', 'fixture-password');
equal(readyDiscovery.enabled, true); equal(readyDiscovery.upload_enabled, true); equal(readyDiscovery.sd_password, 'fixture-password');
for (const args of [[discoveryCamera, '', []], [discoveryCamera, 'a'.repeat(121), []], [{host: 'bad.local'}, 'PN', []], [discoveryCamera, 'PN', [{id: 'pn', host: '192.168.31.166'}]], [discoveryCamera, 'PN', [], 'admin', 'a'.repeat(65)], [discoveryCamera, 'PN', [], 'admin', '\0']]) { checks++; assert.throws(() => helpers.discoveryPayload(...args)); }

// Exercise the real rendering functions without a browser or third-party DOM package.
const fs = require('node:fs'), vm = require('node:vm'), path = require('node:path');
const markup = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
const stylesheet = fs.readFileSync(path.join(__dirname, 'style.css'), 'utf8');
const source = fs.readFileSync(path.join(__dirname, 'app.js'), 'utf8');
equal(markup.includes('href="#logs" class="nav-item" data-view="logs"'), true);
equal(markup.includes('id="view-logs"'), true);
equal((markup.match(/id="sync-jobs"/g) || []).length, 1);
equal(markup.indexOf('id="sync-jobs"') > markup.indexOf('id="view-logs"'), true);
equal(markup.slice(markup.indexOf('id="view-cameras"'), markup.indexOf('id="view-archive"')).includes('sync-job-list'), false);
equal(source.includes('/api/sync?limit=100'), true);
equal(source.includes('jobs.slice(0, 6)'), false);
equal(stylesheet.includes('text-overflow:ellipsis'), true);
equal(stylesheet.includes('.sync-row-summary:focus-visible'), true);
equal(stylesheet.includes('grid-template-columns:75px minmax(0,1fr) max-content 43px'), true);
equal(markup.includes('id="discover-camera-button"'), true);
equal(markup.includes('id="add-camera-button"'), true);
equal(markup.includes('id="discovery-dialog" aria-labelledby="discovery-dialog-title"'), true);
equal(markup.includes('id="discovery-progress-label" class="small" role="status" aria-live="polite"'), true);
equal(markup.includes('id="discovery-sd-password" type="password"'), true);
equal(stylesheet.includes('.discovery-results{grid-template-columns:1fr}'), true);
equal(stylesheet.includes('.discovery-credentials>summary:focus-visible'), true);
equal(source.includes('discovery_scan_id: d.scan.id'), true);
equal(source.includes('const {sd_password, ...metadata} = payload'), true);
equal(markup.includes('id="camera-channel-select"'), true);
equal(markup.includes('Gắn với channel'), true);
equal(markup.includes('id="camera-channel-chat-id" name="channel_chat_id" type="text"'), true);
equal(markup.includes('id="camera-channel-directory-note" class="field-hint" role="status" aria-live="polite"'), true);
equal(stylesheet.includes('.channel-manual>summary:focus-visible'), true);

class Element {
  constructor(tag = 'div') {
    this.tagName = tag.toUpperCase(); this.childNodes = []; this.dataset = {}; this.attributes = {}; this.listeners = {}; this.hidden = false; this.open = false; this.className = ''; this._text = ''; this._value = undefined;
    this.classList = {toggle: (name, force) => {const classes = new Set(this.className.split(/\s+/).filter(Boolean)); const enabled = force ?? !classes.has(name); if (enabled) classes.add(name); else classes.delete(name); this.className = [...classes].join(' ');}};
  }
  append(...children) { this.childNodes.push(...children); }
  replaceChildren(...children) { this.childNodes = [...children]; this._text = ''; if (this.tagName === 'SELECT') this._value = undefined; }
  get textContent() { return this._text + this.childNodes.map(child => typeof child === 'string' ? child : child.textContent).join(''); }
  set textContent(value) { this._text = String(value); this.childNodes = []; }
  get value() { return this._value ?? (this.tagName === 'SELECT' ? this.childNodes[0]?.value : '') ?? ''; }
  set value(value) { this._value = String(value); }
  set innerHTML(value) { this.rawHtml = value; }
  setAttribute(name, value) { this.attributes[name] = String(value); }
  getAttribute(name) { return this.attributes[name] ?? null; }
  removeAttribute(name) { delete this.attributes[name]; }
  addEventListener(name, callback) { (this.listeners[name] ||= []).push(callback); }
  fire(name) { for (const callback of this.listeners[name] || []) callback({target: this}); }
  focus() { documentStub.activeElement = this; }
  showModal() { this.open = true; }
  close() { this.open = false; this.fire('close'); }
  reset() { this.resetCount = (this.resetCount || 0) + 1; }
  querySelectorAll(selector) {
    const matches = element => selector === 'details[data-sync-key]' ? element.tagName === 'DETAILS' && element.dataset.syncKey : selector === 'summary' ? element.tagName === 'SUMMARY' : selector === 'button' ? element.tagName === 'BUTTON' : false;
    return this.childNodes.flatMap(child => child instanceof Element ? [...(matches(child) ? [child] : []), ...child.querySelectorAll(selector)] : []);
  }
  querySelector(selector) { return this.querySelectorAll(selector)[0] || null; }
}
const elements = new Map();
for (const match of markup.matchAll(/<([a-z]+)[^>]*\bid="([^"]+)"[^>]*>/g)) elements.set(match[2], new Element(match[1]));
const viewNodes = ['cameras', 'archive', 'logs', 'system'].map(name => {const item = elements.get('view-' + name); item.id = 'view-' + name; return item;});
const navNodes = viewNodes.map(item => {const link = new Element('a'); link.dataset.view = item.id.slice(5); return link;});
const documentStub = {activeElement: null, getElementById: id => elements.get(id), createElement: tag => new Element(tag), createElementNS: (_, tag) => new Element(tag), querySelectorAll: selector => selector === '.view' ? viewNodes : selector === '[data-view]' ? navNodes : [], contains: target => {
  const contains = element => element === target || element.childNodes.some(child => child instanceof Element && contains(child));
  return [...elements.values()].some(contains);
}};
const context = {document: documentStub, Node: Element, module: {exports: {}}, window: {addEventListener() {}}, location: {hash: '#cameras'}, URL, TextEncoder, Date, Intl, setTimeout, clearTimeout};
vm.createContext(context);
const bootLine = 'switchView(location.hash.slice(1), false); boot();';
equal(source.includes(bootLine), true);
vm.runInContext(source.replace(bootLine, 'globalThis.testUi = {state, renderCameras, renderSync, renderLogs, switchView, syncDisclosure, renderDiscoveryJob, renderDiscoveryResults, discoveryControls, closeDiscovery, resetDiscovery, openDiscovery, startDiscovery, pollDiscovery, cancelDiscovery, addDiscoveredCameras, renderChannelOptions, loadCameraChannels, checkCameraChannel};'), context);
const ui = context.testUi;
ui.state.cameras = [{id: 'pn', name: 'PN', enabled: true, host: '192.168.1.2'}, {id: 'door', name: 'Cửa trước', enabled: true}];
const job = {id: 'job-1', camera_id: 'pn', camera_name: 'PN', state: 'running', phase: 'uploading', message: '<img src=x onerror=alert(1)>', code: 'fixture_code', source: 'dashboard', created_at: 100, started_at: 101, updated_at: 102, finished_at: null, statistics: {sd_searched: 27, sd_downloaded: 27, uploaded: 16, failed: 0, remuxed: 20, sd_error_code: 'fixture_error'}};
ui.state.sync = {jobs: [job], latest: {pn: job}, worker_alive: true};
ui.renderSync(); ui.renderCameras();
equal(elements.get('sync-summary').textContent, '1 đang chạy · 0 chờ · 0 cần xử lý');
equal(elements.get('sync-jobs').querySelectorAll('details[data-sync-key]').length, 1);
equal(elements.get('camera-grid').querySelectorAll('details[data-sync-key]').length, 2);
let logRow = elements.get('sync-jobs').childNodes[0];
equal(logRow.tagName, 'DETAILS');
equal(logRow.childNodes[0].tagName, 'SUMMARY');
equal(logRow.open, false);
equal(logRow.textContent.includes(job.message), true);
equal(logRow.childNodes[1].childNodes[0].rawHtml, undefined);
equal(logRow.textContent.includes('Đã remux20'), true);
equal(logRow.textContent.includes('Mã lỗi SDfixture_error'), true);
equal(logRow.childNodes[0].getAttribute('aria-label').includes('Chi tiết đồng bộ PN'), true);
equal(logRow.childNodes[0].getAttribute('aria-label').includes('Đang chạy · Upload Telegram · SD 27'), true);
logRow.open = true; logRow.fire('toggle'); logRow.childNodes[0].focus();
ui.state.sync.jobs[0] = {...job, statistics: {...job.statistics, uploaded: 17}};
ui.renderLogs();
logRow = elements.get('sync-jobs').childNodes[0];
equal(logRow.open, true);
equal(documentStub.activeElement, logRow.childNodes[0]);
equal(logRow.childNodes[0].textContent.includes('Upload 17'), true);
logRow.open = false; logRow.fire('toggle'); ui.renderLogs();
equal(elements.get('sync-jobs').childNodes[0].open, false);
let cameraRow = elements.get('camera-grid').querySelectorAll('details[data-sync-key]')[0];
cameraRow.open = true; cameraRow.fire('toggle'); cameraRow.childNodes[0].focus(); ui.renderCameras();
cameraRow = elements.get('camera-grid').querySelectorAll('details[data-sync-key]')[0];
equal(cameraRow.open, true);
equal(documentStub.activeElement, cameraRow.childNodes[0]);
ui.state.sync.latest.pn = {...job, id: 'job-2'}; ui.renderCameras();
equal(elements.get('camera-grid').querySelectorAll('details[data-sync-key]')[0].open, true);
elements.get('logs-camera').value = 'door'; ui.renderLogs();
equal(elements.get('sync-jobs').childNodes.length, 0);
equal(elements.get('logs-empty').hidden, false);
elements.get('logs-camera').value = ''; elements.get('logs-status').value = 'errors'; ui.renderLogs();
equal(elements.get('sync-jobs').childNodes.length, 0);
elements.get('logs-status').value = ''; ui.renderLogs();
equal(elements.get('sync-jobs').childNodes.length, 1);
logRow = elements.get('sync-jobs').childNodes[0]; logRow.open = true; logRow.fire('toggle');
elements.get('logs-camera').value = 'door'; ui.renderLogs();
elements.get('logs-camera').value = ''; ui.renderLogs();
equal(elements.get('sync-jobs').childNodes[0].open, true);
// An old node's delayed close event must not erase the new node's remembered state.
logRow.open = false; logRow.fire('toggle'); ui.renderLogs();
equal(elements.get('sync-jobs').childNodes[0].open, true);
ui.switchView('logs', false);
equal(elements.get('view-logs').hidden, false);
equal(elements.get('view-cameras').hidden, true);
equal(elements.get('topbar-page').textContent, 'Logs');
equal(navNodes.find(item => item.dataset.view === 'logs').getAttribute('aria-current'), 'page');
ui.state.sync.jobs = []; ui.renderLogs();
equal(elements.get('logs-empty').textContent.includes('Chưa có lịch sử'), true);
// Channel mapping remains explicit, named and unique; untrusted titles are text.
ui.state.editing = 'pn'; elements.get('camera-channel-chat-id').value = '-1001234567890';
const directory = [{chat_id: -1001234567890, name: '<img src=x onerror=alert(1)>', bound_camera_id: 'pn', ready: true, private: true}, {chat_id: -1002234567890, name: 'Sân', bound_camera_id: 'door', ready: true, private: true}, {chat_id: -1003234567890, name: 'Cổng', ready: false, private: true}, {chat_id: -1004234567890, name: 'Public', private: false}];
ui.renderChannelOptions(directory);
equal(elements.get('camera-channel-select').value, '-1001234567890');
equal(elements.get('camera-channel-select').childNodes.length, 4);
equal(elements.get('camera-channel-select').childNodes[1].textContent, directory[0].name);
equal(elements.get('camera-channel-select').childNodes[1].rawHtml, undefined);
equal(elements.get('camera-channel-select').childNodes[1].disabled, false);
equal(elements.get('camera-channel-select').childNodes[2].disabled, true);
equal(elements.get('camera-channel-select').childNodes[3].textContent, 'Cổng · cần kiểm tra');
ui.renderChannelOptions([], '-1001234567890');
equal(elements.get('camera-channel-select').value, '-1001234567890');
equal(elements.get('camera-channel-select').childNodes[1].textContent.includes('channel đang gán'), true);
ui.renderChannelOptions(directory, '');
equal(elements.get('camera-channel-select').value, '');
equal(elements.get('camera-channel-select').childNodes[0].value, '');
elements.get('camera-channel-select').value = '-1003234567890'; elements.get('camera-channel-select').fire('change');
equal(elements.get('camera-channel-chat-id').value, '-1003234567890');
ui.state.status.multi_channel_routing = true;
ui.state.cameras = [{id: 'pn', name: 'PN', host: '192.168.1.2', channel_chat_id: -1001234567890, channel_status: 'ready', channel_index_url: 'https://t.me/c/1234567890/20'}, {id: 'door', name: 'Cửa trước', channel_enabled: true}];
ui.renderCameras();
equal(elements.get('camera-grid').childNodes[0].textContent.includes('Channel sẵn sàng'), true);
equal(elements.get('camera-grid').childNodes[0].textContent.includes('Mở mục lục channel'), true);
equal(elements.get('camera-grid').childNodes[1].textContent.includes('không gửi sang channel khác'), true);
equal(elements.get('camera-grid').childNodes[1].querySelectorAll('button').find(control => control.dataset.cameraChannel === 'door').disabled, true);
// Render scan results with untrusted labels as text and keep edits through polling.
elements.get('discovery-dialog').open = true;
ui.renderDiscoveryJob({id: 'scan-1', target: '192.168.31.0/24', state: 'running', total: 254, scanned: 80, results: [discoveryCamera, {host: '192.168.31.137', model: '<img src=x onerror=alert(1)>', vendor: 'fixture', confidence: 'identified', ports: [8000, 554]}]});
equal(elements.get('discovery-results').childNodes.length, 2);
equal(Number(elements.get('discovery-progress').value), 80);
equal(elements.get('discovery-progress').max, 254);
equal(elements.get('discovery-start').disabled, true);
equal(elements.get('discovery-cancel').hidden, false);
equal(elements.get('discovery-results').textContent.includes('<img src=x onerror=alert(1)>'), true);
equal(elements.get('discovery-results').childNodes[1].childNodes[1].rawHtml, undefined);
const choices = ui.state.discovery.choices;
const discoveryChoice = choices.get('192.168.31.137'), originalElement = discoveryChoice.element;
discoveryChoice.nameInput.value = 'Sân trước'; discoveryChoice.nameInput.fire('input');
discoveryChoice.check.checked = true; discoveryChoice.check.fire('change');
equal(discoveryChoice.name, 'Sân trước'); equal(discoveryChoice.selected, true);
equal(elements.get('discovery-add').disabled, true);
ui.renderDiscoveryJob({id: 'scan-1', target: '192.168.31.0/24', state: 'completed', total: 254, scanned: 254, results: [{...discoveryCamera, confidence: 'candidate', ports: [8000, 554]}, {...discoveryChoice.result}]});
equal(discoveryChoice.element, originalElement);
equal(discoveryChoice.nameInput.value, 'Sân trước');
equal(discoveryChoice.check.checked, true);
equal(elements.get('discovery-add').disabled, false);
equal(elements.get('discovery-add').textContent, 'Thêm camera đã chọn (1)');
equal(elements.get('discovery-cancel').hidden, true);
elements.get('discovery-select-all').checked = true; elements.get('discovery-select-all').fire('change');
equal(elements.get('discovery-add').textContent, 'Thêm camera đã chọn (2)');
ui.state.cameras.push({id: 'known-c6n', name: 'Đã có', host: discoveryCamera.host, device_port: 8000}); ui.renderDiscoveryResults();
equal(choices.get(discoveryCamera.host).check.disabled, true);
equal(choices.get(discoveryCamera.host).status.textContent, 'Đã cấu hình · Đã có');
equal(elements.get('discovery-add').textContent, 'Thêm camera đã chọn (1)');
discoveryChoice.error = '<script>fixture-error</script>'; ui.renderDiscoveryResults();
equal(discoveryChoice.status.textContent, '<script>fixture-error</script>');
equal(discoveryChoice.status.rawHtml, undefined);
ui.state.discovery.adding = true; ui.renderDiscoveryResults();
equal(discoveryChoice.check.disabled, true); equal(discoveryChoice.nameInput.disabled, true);
equal(elements.get('close-discovery-dialog').disabled, true);
equal(elements.get('discovery-sd-password').disabled, true);
ui.state.discovery.adding = false; elements.get('discovery-sd-password').value = 'fixture-password';
const discoveryRevision = ui.state.discovery.revision;
ui.resetDiscovery();
equal(elements.get('discovery-dialog').open, false);
equal(elements.get('discovery-sd-password').value, '');
equal(ui.state.discovery.scan, null); equal(ui.state.discovery.choices.size, 0);
equal(ui.state.discovery.revision, discoveryRevision + 1);
// Exercise real async paths with synthetic API replies, never LAN traffic.
(async () => {
  const requests = [], apiCameras = [], fixtureResults = [{host: '192.168.5.10', ports: [8000, 554], confidence: 'candidate'}, {host: '192.168.5.11', ports: [8000, 554, 80], model: 'CS-H6c', vendor: 'EZVIZ', confidence: 'identified'}];
  const scanReply = state => ({scan: {id: 'fixture-scan', target: '192.168.5.0/24', state, total: 254, scanned: state === 'running' ? 50 : 254, results: fixtureResults}});
  let addFailure = null;
  context.setTimeout = () => 321; context.clearTimeout = () => {};
  context.fetch = async (url, options) => {
    requests.push({url, ...options}); let status = 200, result;
    if (url === '/api/discovery/subnets') result = {subnets: [{cidr: '192.168.5.0/24', source: 'tailscale', interface: 'tailscale0'}, {cidr: '10.2.0.0/24', source: 'lan', interface: 'eth0'}], stale: false};
    else if (url === '/api/discovery/scans') result = scanReply('running');
    else if (url === '/api/discovery/scans/fixture-scan/cancel') result = scanReply('cancelled');
    else if (url === '/api/discovery/scans/fixture-scan') result = scanReply('completed');
    else if (url === '/api/cameras' && options.method === 'POST') {
      const payload = JSON.parse(options.body);
      if (addFailure) { status = addFailure.status; result = addFailure.result; }
      else { const {sd_password, discovery_scan_id, ...metadata} = payload; apiCameras.push(metadata); result = {camera: metadata}; }
    } else if (url === '/api/status') result = {csrf_token: 'fixture-csrf', counts: {recordings: 0, uploaded: 0}};
    else if (url === '/api/cameras') result = {cameras: apiCameras};
    else if (url === '/api/sync?limit=100') result = {jobs: [], latest: {}, worker_alive: true};
    else throw new Error('Unexpected fixture request: ' + url);
    return {ok: status < 400, status, json: async () => JSON.parse(JSON.stringify(result))};
  };
  ui.state.authenticated = true; ui.state.csrf = 'fixture-csrf'; ui.state.cameras = [];
  elements.get('account-screen').hidden = true;
  await ui.openDiscovery();
  equal(elements.get('discovery-dialog').open, true);
  equal(elements.get('discovery-subnet').childNodes.length, 3);
  equal(elements.get('discovery-subnet').childNodes[1].textContent.includes('Tailscale'), true);
  elements.get('discovery-subnet').value = '192.168.5.0/24'; elements.get('discovery-subnet').fire('change');
  equal(elements.get('discovery-target').value, '192.168.5.0/24');
  equal(documentStub.activeElement, elements.get('discovery-target'));
  await ui.startDiscovery({preventDefault() {}});
  const startRequest = requests.find(request => request.url === '/api/discovery/scans');
  equal(JSON.parse(startRequest.body), {target: '192.168.5.0/24'});
  equal(startRequest.headers['X-CSRF-Token'], 'fixture-csrf');
  equal(startRequest.credentials, 'same-origin');
  equal(ui.state.discovery.scan.state, 'running');
  equal(ui.state.discovery.timer, 321);
  await ui.cancelDiscovery();
  equal(ui.state.discovery.scan.state, 'cancelled');
  equal(ui.state.discovery.timer, null);
  equal(elements.get('discovery-start').disabled, false);
  equal(requests.some(request => request.url.endsWith('/cancel') && request.method === 'POST'), true);
  await ui.startDiscovery({preventDefault() {}});
  await ui.pollDiscovery(ui.state.discovery.revision, ui.state.sessionRevision);
  equal(ui.state.discovery.scan.state, 'completed');
  const firstChoice = ui.state.discovery.choices.get('192.168.5.10'); firstChoice.selected = true; firstChoice.name = 'Sân sau';
  elements.get('discovery-sd-password').value = '';
  await ui.addDiscoveredCameras();
  const draftRequest = JSON.parse(requests.find(request => request.url === '/api/cameras' && request.method === 'POST').body);
  equal(draftRequest.discovery_scan_id, 'fixture-scan');
  equal(draftRequest.enabled, false); equal(draftRequest.upload_enabled, true);
  equal(draftRequest.sd_password, undefined); equal(draftRequest.name, 'Sân sau');
  equal(firstChoice.added, true); equal(firstChoice.selected, false);
  equal(elements.get('discovery-add-status').textContent.includes('Đang tạm dừng'), true);
  const secondChoice = ui.state.discovery.choices.get('192.168.5.11'); secondChoice.selected = true;
  elements.get('discovery-sd-password').value = 'fixture-password';
  await ui.addDiscoveredCameras();
  const readyRequest = JSON.parse(requests.filter(request => request.url === '/api/cameras' && request.method === 'POST').at(-1).body);
  equal(readyRequest.enabled, true); equal(readyRequest.sd_password, 'fixture-password');
  equal(ui.state.cameras.every(camera => !('sd_password' in camera)), true);
  equal(elements.get('discovery-sd-password').value, '');
  equal(elements.get('discovery-add-status').textContent.includes('Đã bật và gửi Start'), true);
  // A fresh conflict from another dashboard session becomes a known camera.
  fixtureResults.push({host: '192.168.5.12', ports: [8000, 554], confidence: 'candidate'});
  ui.renderDiscoveryJob(scanReply('completed').scan);
  const thirdChoice = ui.state.discovery.choices.get('192.168.5.12'); thirdChoice.selected = true;
  apiCameras.push({id: 'already-added', name: 'Cửa trước', host: '192.168.5.12', device_port: 8000});
  addFailure = {status: 409, result: {code: 'camera_already_exists', existing_camera_id: 'already-added', error: 'Camera already exists'}};
  await ui.addDiscoveredCameras();
  equal(thirdChoice.result.existing_camera_id, 'already-added');
  equal(thirdChoice.selected, false); equal(thirdChoice.check.disabled, true);
  equal(elements.get('discovery-add-status').textContent.includes('1 đã có sẵn'), true);
  equal(ui.state.cameras.some(camera => camera.id === 'already-added'), true);
  addFailure = null;
  // Responses from a closed dialog must not repopulate its cleared state.
  let resolveLate;
  context.fetch = () => new Promise(resolve => { resolveLate = resolve; });
  const latePoll = ui.pollDiscovery(ui.state.discovery.revision, ui.state.sessionRevision);
  ui.closeDiscovery();
  resolveLate({ok: true, status: 200, json: async () => scanReply('completed')});
  await latePoll;
  equal(ui.state.discovery.scan, null); equal(ui.state.discovery.choices.size, 0);
  equal(ui.state.discovery.timer, null); equal(elements.get('discovery-dialog').open, false);
  // Directory refresh and verify use the same authenticated API client.
  ui.state.authenticated = true; ui.state.csrf = 'fixture-csrf';
  ui.state.channelFormRevision = 1; elements.get('camera-dialog').open = true;
  elements.get('camera-channel-chat-id').value = '-1001234567890';
  context.fetch = async (url, options) => { requests.push({url, ...options}); return {ok: true, status: 200, json: async () => ({channels: directory})}; };
  await ui.loadCameraChannels();
  equal(elements.get('camera-channel-select').value, '-1001234567890');
  equal(elements.get('camera-channel-refresh').disabled, false);
  await ui.loadCameraChannels(true);
  const directoryRequest = requests.find(request => request.url === '/api/telegram/channels/refresh');
  equal(directoryRequest.method, 'POST'); equal(JSON.parse(directoryRequest.body), {}); equal(directoryRequest.headers['X-CSRF-Token'], 'fixture-csrf');
  const mappedCamera = {id: 'pn', name: 'PN', channel_chat_id: -1001234567890, channel_status: 'unconfigured', upload_enabled: true};
  ui.state.cameras = [mappedCamera];
  context.fetch = async (url, options) => { requests.push({url, ...options}); return {ok: true, status: 200, json: async () => ({camera: {...mappedCamera, channel_status: 'ready'}, ready: true})}; };
  await ui.checkCameraChannel(mappedCamera);
  equal(ui.state.cameras[0].channel_status, 'ready'); equal(ui.state.cameras[0].upload_enabled, true);
  const checkRequest = requests.find(request => request.url === '/api/cameras/pn/channel-check');
  equal(checkRequest.method, 'POST'); equal(JSON.parse(checkRequest.body), {}); equal(checkRequest.headers['X-CSRF-Token'], 'fixture-csrf');
  // A late directory response cannot alter a closed/reopened camera form.
  context.fetch = () => new Promise(resolve => { resolveLate = resolve; });
  const lateDirectory = ui.loadCameraChannels();
  const oldDirectory = ui.state.knownChannels;
  elements.get('camera-dialog').close();
  resolveLate({ok: true, status: 200, json: async () => ({channels: []})}); await lateDirectory;
  equal(ui.state.knownChannels, oldDirectory);
  console.log(`WEB_HELPERS: checks=${checks} passed=${checks} failed=0`);
})().catch(error => { console.error(error); process.exitCode = 1; });
