"use strict";
const assert = require("node:assert/strict");
const helpers = require("./app.js");
let checks = 0;
function equal(actual, expected) { checks++; assert.deepEqual(actual, expected); }
equal(helpers.formatBytes(null), "—");
equal(helpers.formatBytes(undefined), "—");
equal(helpers.formatBytes("n/a"), "—");
equal(helpers.formatBytes(-1), "—");
equal(helpers.formatBytes(0), "0 B");
equal(helpers.formatBytes(1024), "1 KB");
equal(helpers.formatBytes(1024 * 1024), "1 MB");
equal(helpers.formatDuration(0, 45000), "45 giây");
equal(helpers.formatDuration(0, 65000), "1 phút 5 giây");
equal(helpers.formatDuration(0, 120000), "2 phút");
equal(helpers.formatDuration(5000, 0), "—");
equal(helpers.formatDuration(null, 0), "—");
const privateLink = "https://t.me/fixture_archive_bot?start=play_" + "a".repeat(32);
equal(helpers.telegramUrl(privateLink), privateLink);
for (const url of ["https://t.me/c/12345/17", privateLink + "&extra=1", privateLink + "#fragment", privateLink.replace("play_", "other_"), privateLink.slice(0, -1), "https://t.me/fixture_archive_bot", privateLink.replace("fixture_archive_bot", "tiny")]) equal(helpers.telegramUrl(url), null);
for (const url of ["javascript:alert(1)", "http://t.me/c/1/2", "https://t.me.evil.example/c/1/2", "https://evil.example/t.me", "https://evil:t.me@t.me/c/1/2", "https://t.me:444/c/1/2", "https://t.me/", null]) equal(helpers.telegramUrl(url), null);
for (const host of ["192.168.1.11", "192.168.1.10", "camera-h6c.local", "camera", "CAMERA-1"]) equal(helpers.validHost(host), true);
for (const host of ["999.168.31.137", "192.168.1.1000", "http://192.168.1.11", "camera.local/path", "camera:8000", "user@camera", "-camera.local", "camera..local", "", "<img>", null]) equal(helpers.validHost(host), false);
equal(helpers.status("uploaded"), ["Đã lưu Telegram", "green"]);
equal(helpers.status("upload_unknown"), ["Cần đối chiếu upload", "amber"]);
equal(helpers.status("needs_review"), ["Cần kiểm tra", "amber"]);
equal(helpers.status("UNRECOGNIZED"), ["UNRECOGNIZED", "neutral"]);
equal(helpers.probeState(true), ["Mở", "green"]);
equal(helpers.probeState({open: true}), ["Mở", "green"]);
equal(helpers.probeState({status: "open"}), ["Mở", "green"]);
equal(helpers.probeState(false), ["Đóng / không phản hồi", "red"]);
equal(helpers.probeState(undefined), ["Chưa kiểm tra", "neutral"]);
equal(helpers.probeState("unconfirmed"), ["Chưa xác nhận", "amber"]);
equal(helpers.checkedMillis(1790989200), 1790989200000);
equal(helpers.checkedMillis("2026-10-03T00:00:00Z"), Date.parse("2026-10-03T00:00:00Z"));
equal(helpers.checkedMillis("bad"), null);
equal(helpers.checkedMillis(null), null);
equal(helpers.cameraCount({counts: {total: 5, uploaded: 4}}, "total"), 5);
equal(helpers.cameraCount({counts: {total: 5, uploaded: 4}}, "uploaded"), 4);
equal(helpers.cameraCount({record_count: 0}, "total"), 0);
equal(helpers.cameraCount({}, "total"), null);
const original = {id: "Front_Camera", name: "Cửa trước", model: "CS-H6c", host: "192.168.1.11", device_port: 8000, rtsp_port: 554, http_port: 80, enabled: true};
equal(helpers.cameraPatch(original, {...original}), {});
equal(helpers.cameraPatch(original, {...original, name: "Sân trước"}), {name: "Sân trước"});
equal(helpers.cameraPatch(original, {...original, host: "192.168.31.138"}), {host: "192.168.31.138"});
equal(helpers.cameraPatch(original, {...original, id: "Changed_Id"}), {});
equal(helpers.cameraPatch(original, {...original, enabled: false}), {enabled: false});
for (const username of ['admin', 'new.admin_1', 'A'.repeat(64)]) equal(helpers.validUsername(username), true);
for (const username of ['ab', 'A'.repeat(65), 'bad name', '<admin>', '', null]) equal(helpers.validUsername(username), false);
const credentials = {username: 'new_admin', current_password: 'admin', new_password: 'new-password-123', confirm_password: 'new-password-123'};
equal(helpers.accountValidation(credentials), null);
equal(helpers.accountValidation({...credentials, username: 'x'}).field, 'account-username');
equal(helpers.accountValidation({...credentials, current_password: ''}).field, 'account-current-password');
equal(helpers.accountValidation({...credentials, new_password: 'short', confirm_password: 'short'}).field, 'account-new-password');
equal(helpers.accountValidation({...credentials, new_password: 'x'.repeat(129)}).field, 'account-new-password');
equal(helpers.accountValidation({...credentials, confirm_password: 'different'}).field, 'account-confirm-password');
equal(helpers.accountValidation({...credentials, new_password: '🔑'.repeat(128), confirm_password: '🔑'.repeat(128)}), null);
equal(helpers.accountValidation({...credentials, new_password: '🔑'.repeat(129), confirm_password: '🔑'.repeat(129)}).field, 'account-new-password');
equal(helpers.uploadEnabled({}), true);
equal(helpers.uploadEnabled({upload_enabled: true}), true);
equal(helpers.uploadEnabled({upload_enabled: false}), false);
equal(helpers.syncActive({state: 'queued'}), true);
equal(helpers.syncActive({state: 'running'}), true);
for (const state of ['completed', 'blocked', 'failed', undefined]) equal(helpers.syncActive({state}), false);
equal(helpers.syncActive(null), false);
equal(helpers.syncState({state: 'blocked'}), ['Cần xử lý', 'amber']);
equal(helpers.syncState({state: 'completed'}), ['Hoàn tất', 'green']);
equal(helpers.syncState(null), ['Chưa Start', 'neutral']);
equal(helpers.syncPhase({phase: 'sd_download'}), 'Tải SD');
equal(helpers.syncPhase({phase: 'uploading'}), 'Upload Telegram');
equal(helpers.syncStatistics({statistics: {sd_searched: 3, sd_downloaded: 2, uploaded: 1, pending: 0, secret: 'notshown'}}), 'Tìm thấy SD: 3 · Đã tải SD: 2 · Đã upload: 1 · Chờ upload: 0');
equal(helpers.syncStatistics({statistics: {uploaded: -1, failed: NaN, imported: '3'}}), '');
equal(helpers.syncHelp({code: 'sd_sdk_missing'}).includes('/opt/hcnetsdk'), true);
equal(helpers.syncHelp({code: 'sd_network_error'}).includes('Tailscale'), true);
equal(helpers.syncHelp({code: 'sd_source_missing'}).includes('8000'), true);
equal(helpers.syncHelp({code: 'sd_credentials_missing'}).includes('mã xác thực'), true);
equal(helpers.syncHelp({code: 'complete'}), '');
equal(helpers.cameraPatch(original, {...original, upload_enabled: false}), {upload_enabled: false});
equal(helpers.cameraPatch(original, {...original, sd_password: ''}), {});
equal(helpers.cameraPatch(original, {...original, sd_password: 'fixture-password'}), {sd_password: 'fixture-password'});
equal(helpers.cameraPatch(original, {...original, sd_password_clear: true}), {sd_password_clear: true});
equal(helpers.cameraPatch(original, {...original, sd_backend: 'hcnetsdk', sd_channel: 1}), {sd_backend: 'hcnetsdk', sd_channel: 1});
equal(helpers.validSdPassword('x'.repeat(64)), true);
equal(helpers.validSdPassword('x'.repeat(65)), false);
equal(helpers.validSdPassword('🔑'.repeat(16)), true);
equal(helpers.validSdPassword('🔑'.repeat(17)), false);
equal(helpers.validSdPassword('x\0x'), false);
console.log(`WEB_HELPERS: checks=${checks} passed=${checks} failed=0`);
